"""empty message

Revision ID: aa6623f52d39
Revises: d8c9fa6fc45a
Create Date: 2023-03-03 16:24:59.315554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa6623f52d39'
down_revision = 'd8c9fa6fc45a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('homeworld', sa.String(length=250), nullable=False),
    sa.Column('birth_year', sa.String(length=250), nullable=False),
    sa.Column('gender', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('terrain', sa.String(length=250), nullable=False),
    sa.Column('gravity', sa.String(length=250), nullable=False),
    sa.Column('climate', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=250), nullable=False),
    sa.Column('starship_class', sa.String(length=250), nullable=False),
    sa.Column('manufacturer', sa.String(length=250), nullable=False),
    sa.Column('length', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('starships')
    op.drop_table('planets')
    op.drop_table('users')
    op.drop_table('characters')
    with op.batch_alter_table('favorite_characters', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_characters_character_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_characters_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Characters', ['character_id'], ['id'])
        batch_op.create_foreign_key(None, 'Users', ['user_id'], ['id'])

    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_planets_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_planets_planet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Planets', ['planet_id'], ['id'])
        batch_op.create_foreign_key(None, 'Users', ['user_id'], ['id'])

    with op.batch_alter_table('favorite_starships', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_starships_starship_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_starships_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Starships', ['starship_id'], ['id'])
        batch_op.create_foreign_key(None, 'Users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_starships', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_starships_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('favorite_starships_starship_id_fkey', 'starships', ['starship_id'], ['id'])

    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_planets_planet_id_fkey', 'planets', ['planet_id'], ['id'])
        batch_op.create_foreign_key('favorite_planets_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('favorite_characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_characters_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('favorite_characters_character_id_fkey', 'characters', ['character_id'], ['id'])

    op.create_table('characters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('homeworld', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('birth_year', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='characters_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_table('planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('terrain', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('gravity', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('climate', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='planets_pkey')
    )
    op.create_table('starships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('starship_class', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('length', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='starships_pkey')
    )
    op.drop_table('Users')
    op.drop_table('Starships')
    op.drop_table('Planets')
    op.drop_table('Characters')
    # ### end Alembic commands ###
